import 'package:testable_web_app/patient/models/patient_model.dart';

const List<PatientModel> seedPatients = [
  PatientModel(
    patientID: 'test',
    patientFirstName: 'testFirstName',
    patientLastName: 'testLastName',
    patientHealthcareRecordNumber: '1232131231',
    patientBirthDate: '15/04/2021',
    clinicID: '',
    ocsPatientLink: -1,
    ocsLastUpdatedAt: '',
    patientLastUpdatedAt: '',
  ),
  PatientModel(
    patientID: 'test',
    patientFirstName: 'testFirstName11111',
    patientLastName: 'testLastName1111',
    patientHealthcareRecordNumber: '1232131231',
    patientBirthDate: '15/04/2021',
    clinicID: '',
    ocsPatientLink: -1,
    ocsLastUpdatedAt: '',
    patientLastUpdatedAt: '',
  ),
  PatientModel(
    patientID: 'test',
    patientFirstName: 'testFirstName',
    patientLastName: 'testLastName222222',
    patientHealthcareRecordNumber: '1232131231',
    patientBirthDate: '15/04/2021',
    clinicID: '',
    ocsPatientLink: -1,
    ocsLastUpdatedAt: '',
    patientLastUpdatedAt: '',
  ),
  PatientModel(
    patientID: 'test',
    patientFirstName: 'testFirstName',
    patientLastName: 'testLastName345345',
    patientHealthcareRecordNumber: '1232131231',
    patientBirthDate: '15/04/2021',
    clinicID: '',
    ocsPatientLink: -1,
    ocsLastUpdatedAt: '',
    patientLastUpdatedAt: '',
  ),
];
