name: Flutter test code coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: "2.0.4"
          channel: "stable"
      - name: Check flutter version (debug)
        run: flutter --version
      - name: Install plugin package dependencies
        run: flutter pub get
      - name: Test
        run: flutter test --coverage

# Bug on flutter test --platform chrome null safety.
# May be similar issue org-dartlang-app root. Strange that this issue is in Flutter 2.0 stable and not in previous beta
# https://github.com/flutter/flutter/issues/71612
# $ flutter test --platform chrome
# org-dartlang-app:///login_models_user_model_test.dart.test.dart:16:171: Error: An escape sequence starting with '\u' must be followed by 4
# hexadecimal digits or from 1 to 6 digits between '{' and '}'.
#     webGoldenComparator =
#     DefaultWebGoldenComparator(Uri.parse('D:\proj\202104-onc-webstore-flutter-web\testable-flutter-interface-sample-web-pwa-mobile\test\login\models\user_model_test.dart'));
#                                                                                                                                       ^^
# Failed to compile
      # - name: Test plugin (web)
      #   run: flutter test --platform chrome --coverage

      # Do not run builds multi repo. codecov requires additional config
      # - name: Build web example project
      #   working-directory: ./example
      #   run: flutter build web

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
